const mongoose = require("mongoose");

const paymentSchema = new mongoose.Schema(
  {
    // customer refrence
    customer: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    // type of the payable entity: ServiceRequest or InventionRequest
    payableType: {
      type: String,
      enum: ["ServiceRequest", "InventionRequest"],
      required: true,
    },

    // refrence to invoices
    payableId: {
      type: mongoose.Schema.Types.ObjectId,
      required: true,
    },

    // amount of the payment in the specified currency
    amount: {
      type: Number,
      required: true,
      min: 0,
    },

    currency: {
      type: String,
      default: "EGP",
      trim: true,
    },

    // type of payment: full or deposit

    paymentType: {
      type: String,
      enum: ["full", "deposit"],
      required: true,
    },

    // payment status
    status: {
      type: String,
      enum: [
        "pending",
        "processing",
        "paid",
        "failed",
        "refunded",
        "cancelled",
      ],
      default: "pending",
    },

    // paymentGateway
    provider: {
      type: String,
      default: "kashier",
      trim: true,
    },

    //  Kashier Payment SessionId
    sessionId: {
      type: String,
      trim: true,
    },

    // when you use Kashier's hosted payment page, this is the ID of the payment link generated by Kashier
    paymentLinkId: {
      type: String,
      trim: true,
    },

    // Transaction ID from Kashier
    transactionId: {
      type: String,
      trim: true,
    },

    // refrecence ID من Kashier
    reference: {
      type: String,
      trim: true,
    },

    //extra data returned by the payment gateway (Kashier)
    gatewayResponse: {
      type: mongoose.Schema.Types.Mixed,
    },

    // history of status changes
    paidAt: {
      type: Date,
    },
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model("Payment", paymentSchema);